config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get 'pages/portfolio' => 'pages#portfolio'
  get 'pages/about' => 'pages#about'
  get 'pages/contact' => 'pages#contact'
  
  resources:route 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  
  def portfolio
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  
 <script src="http://www.google.com/jsapi" type="text/javascript"></script>
 
<script type="text/javascript">google.load("jquery", "1.3.2");</script>
 
</head>
<body>
<div class="header ">
  <div class="container">
    <div class="row">
      <div class="col-md-1"></div>
     	 <div class="col-md-7">
       	 <ul class= " nav navbar-nav">
           <li class="active" ><%= link_to root_path do %>Welcome<%end%></li>
           <li><%= link_to pages_portfolio_path do %>Portfolio<%end%></li>
           <li><%= link_to "Blog", "https://www.medium.com/@aBOmOHAB", :target => "_blank" %></li>
           <li><%= link_to pages_about_path do %> About <%end%></li>
           <li><%= link_to pages_contact_path do %>Contact<%end%></li>
          </ul>
         </div>
      
      <div class="col-md-3">
        <h3>Abo Mohab</h3>
      </div>
      
      <div class="col-md-1"></div>
    </div>
  </div>
</div>
  
<%= yield %>

  
  <div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-1"></div>
      
      <div id="footer" class="col-md-10">
        <div class="inline">
       <a href="#"> <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSc-CVky3U-9hgX1FmeNXNSDTjGoD1B4jWM48qgLhpCk7HA0p6N" /> </a>
         <a href="#"> <img src="http://static1.squarespace.com/static/52440ddbe4b03b33d728e5ea/53c64093e4b0375fd98e1cac/53c64093e4b0375fd98e1cb0/1412749046621/linkedin.png" /> </a>
         <a href="#"> <img src =" http://dandelion.github.io/slides/dandelion-0.10.0/assets/images/logo_github_small.gif" /></a>
        </div><br>

    <p>&copy all rights reserved, Abo Mohab 2015</p>

        </div>
          <div class="col-md-1"></div>
    </div>
  </div>
</div>
  
  
  
</body>
</html>

app/views/pages/about.html.erb
<div class="about">
<div class="row">
<div class="col-md-1"></div>
  
<div class="col-md-4 photo">
<img src="http://goo.gl/FVIySb" />  
</div>
  
<div class="col-md-4 text">
  <h2><span>"Salut" I'm Abo Mohab </span></h2>
  <p>I was born in 1982 in Yemen, I studied there computer science and I work as a technical support.
    Recently I work hard to develop my skills in coding and web app developing and here I am ,<span>"Bis Bald" </span></p>
</div>


<div class="col-md-3"></div>
</div>
</div>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4 line"></div>
</div>

app/views/pages/contact.html.erb
<div class="contacts">
  <div class="row">
    
    
    
    <div class="col-md-12">
      <h2 id="contct"> &#9993; Contact me  </h2> 
      <br>
      <br>
      <br>
        <div class="social">
          
  <a href="#" class="facebook">
  <img id="face" src="http://goo.gl/9PwYVG" />
  </a >
        
        <a href="#" class="twitter">
  <img src="http://goo.gl/LlfI3k" />
  </a >
        
        <a href="#" class="google">
  <img src="http://goo.gl/FFfKKd" />
  </a >
        
        <a href="#" class="linkedin">
  <img src="http://goo.gl/kKsHvJ" />
  </a >
        
         <a href ="#" class="whatsapp">
  <img src="http://goo.gl/YjklKA" />
  </a >
   <a href="#" class="email">
           <img src="https://goo.gl/KmpIah" />
 <!-- <img src="http://goo.gl/GydvOC" />-->
  </a >
      </div>
		</div>
    
	</div>
</div>
  

app/views/pages/portfolio.html.erb
<div class="banner"> 
  
<ul> 
  <li><img src="http://store2.up-00.com/2015-10/1445185588711.jpg" /></li> 
  <li><img src="http://store2.up-00.com/2015-10/1445328268511.jpg" /> </li> 
  <li><img src="http://store2.up-00.com/2015-10/1445185385451.jpg" /> </li> 
  <li><img src="http://store1.up-00.com/2015-10/1445328353791.jpg" /> </li> 

</ul> 
     
</div>
  
<div class="supporting">
  <div class="container">
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
        <div class="threadly">

         
        <%= link_to "https://dry-plateau-6922.herokuapp.com/",:target =>"_blank" ,:class =>"app"    do %>
        <img class="img-responsive" src="http://store2.up-00.com/2015-10/1445185385451.jpg" />
        <h3>Threadly App</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis enim in eros vestibulum mollis sit amet sed turpis. Aenean ut diam in ex dignissim facilisis. Nam eget venenatis diam. </p>
        
        <%end%>
          </div>
      </div>
      
      <div class="col-md-5">
         <%= link_to pages_portfolio_path ,{:class => "app"} do %>
        <img class="img-responsive" src="http://store2.up-00.com/2015-10/1445182643071.png" />
        <h3>Innovation cloud App2</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis enim in eros vestibulum mollis sit amet sed turpis. Aenean ut diam in ex dignissim facilisis. Nam eget venenatis diam. </p>
        <%end%>
      </div>
      
      <div class="col-md-1"></div>
    </div>
    
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-5">
         <%= link_to pages_portfolio_path ,{:class => "app"} do %> 
        <img class="img-responsive" src="http://store2.up-00.com/2015-10/1445185588711.jpg" />
        <h3>Broadway App</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis enim in eros vestibulum mollis sit amet sed turpis. Aenean ut diam in ex dignissim facilisis. Nam eget venenatis diam. </p>
        <%end%>
      </div>
      
      <div class="col-md-5">

        <%= link_to "https://afternoon-basin-9564.herokuapp.com",:target =>"_blank" ,:class =>"app"    do %>
       
        <img class="img-responsive" src="http://store1.up-00.com/2015-11/1447691605891.jpg" />
        <h3>Stories Project</h3>

        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis enim in eros vestibulum mollis sit amet sed turpis. Aenean ut diam in ex dignissim facilisis. Nam eget venenatis diam. </p>
        <%end%>
      </div>
      
      <div class="col-md-1"></div>
    </div>
   
  </div>
</div>
  

app/views/pages/welcome.html.erb
<!-- the header will be copied to application.html.erb
<div class="header ">
  <div class="container">
    <div class="row">
      <div class="col-md-1"></div>
     	 <div class="col-md-7">
       	 <ul class= " nav navbar-nav">
         	  <li class="active" ><a href="#">Welcome</a></li>
             <li><a href ="#">Portfolio</a></li>
             <li><a href="#">Blog</a></li>
             <li><a href="#">About</a></li>
             <li><a href="#">Contact</a></li>
          </ul>
         </div>
      
      <div class="col-md-3">
        <h3>Abo Mohab</h3>
      </div>
      
      <div class="col-md-1"></div>
    </div>
  </div>
</div>
    -->
<div class="main">
  <div class="container">
    <div class="row">
      <div class="col-md-1"></div>
      
      <div class="col-md-10">
        <h1>Hello. My name is <span> Abo Mohab  </span>  and I have creative ideas and build</h1>
        <h1>websites</h1>
        <%= link_to pages_portfolio_path do %>View my Work<%end%>
        </div>
      <div class="col-md-1"></div>
      </div>
  </div>
</div>

<!-- the footer will be copied to application.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-1"></div>
      
      <div class="col-md-10">
        <div class="inline">
       <a href="#"> <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSc-CVky3U-9hgX1FmeNXNSDTjGoD1B4jWM48qgLhpCk7HA0p6N" /> </a>
         <a href="#"> <img src="http://static1.squarespace.com/static/52440ddbe4b03b33d728e5ea/53c64093e4b0375fd98e1cac/53c64093e4b0375fd98e1cb0/1412749046621/linkedin.png" /> </a>
         <a href="#"> <img src =" http://dandelion.github.io/slides/dandelion-0.10.0/assets/images/logo_github_small.gif" /></a>
        </div><br>

    <p>&copy all rights reserved, Abo Mohab 2015</p>

        </div>
          <div class="col-md-1"></div>
    </div>
  </div>
</div> -->